default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: foxy_dev

test:
  <<: *default
  database: foxy_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['POSTGRESQL_URL'] %>